spring:
  h2:
    console:
      enabled: true # H2 Console , UI? ??????? ??
      path: /h2-console # H2 Console ? ??
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test # ?????? ?? ??
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    # hibernate 가 남기는 모든 로그가 debug모드로 설정
    # jpa hibernate가 생성하는 sql이 로거를 통해서 찍히도록 하는 설정
    org.hibernate.SQL: debug
    org.hibernate.type: trace # 실제 들어가는 파라미터값 찍어주는 설정